import type Database from 'better-sqlite3';
import type { PatternRow } from '@bunqsy/shared';

export interface InsertPatternInput {
  id: string;
  name: string;
  description: string;
  triggerConditions: Record<string, unknown>;
  interventionTemplate: Record<string, unknown>;
  confidence?: number;
}

/**
 * Returns all enabled patterns ordered by confidence descending.
 */
export function getAllEnabledPatterns(db: Database.Database): PatternRow[] {
  return db
    .prepare(
      `SELECT * FROM patterns
       WHERE enabled = 1
       ORDER BY confidence DESC`,
    )
    .all() as PatternRow[];
}

/**
 * Returns all patterns regardless of enabled state (used by Dream Mode).
 */
export function getAllPatterns(db: Database.Database): PatternRow[] {
  return db
    .prepare(`SELECT * FROM patterns ORDER BY confidence DESC`)
    .all() as PatternRow[];
}

/**
 * Returns a single pattern by ID, or undefined if not found.
 */
export function getPattern(
  db: Database.Database,
  id: string,
): PatternRow | undefined {
  return db
    .prepare(`SELECT * FROM patterns WHERE id = ?`)
    .get(id) as PatternRow | undefined;
}

/**
 * Inserts a new pattern. Trigger conditions and intervention template are
 * serialised from objects to JSON strings.
 */
export function insertPattern(
  db: Database.Database,
  pattern: InsertPatternInput,
): void {
  db.prepare(`
    INSERT INTO patterns
      (id, name, description, trigger_conditions, intervention_template,
       confidence, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
  `).run(
    pattern.id,
    pattern.name,
    pattern.description,
    JSON.stringify(pattern.triggerConditions),
    JSON.stringify(pattern.interventionTemplate),
    pattern.confidence ?? 0.5,
  );
}

/**
 * Replaces the confidence value of a pattern.
 * Confidence must be in [0.0, 1.0].
 */
export function updatePatternConfidence(
  db: Database.Database,
  id: string,
  confidence: number,
): void {
  db.prepare(
    `UPDATE patterns
     SET confidence = ?, updated_at = datetime('now')
     WHERE id = ?`,
  ).run(Math.min(1, Math.max(0, confidence)), id);
}

/**
 * Increments hit_count by 1 — called each time the pattern fires.
 */
export function incrementHitCount(db: Database.Database, id: string): void {
  db.prepare(
    `UPDATE patterns
     SET hit_count = hit_count + 1, updated_at = datetime('now')
     WHERE id = ?`,
  ).run(id);
}

/**
 * Increments confirmed_count by 1 — called when the user confirms an
 * intervention generated by this pattern.
 */
export function incrementConfirmedCount(
  db: Database.Database,
  id: string,
): void {
  db.prepare(
    `UPDATE patterns
     SET confirmed_count = confirmed_count + 1, updated_at = datetime('now')
     WHERE id = ?`,
  ).run(id);
}

/**
 * Increments dismissed_count by 1 — called when the user dismisses an
 * intervention generated by this pattern.
 */
export function incrementDismissedCount(
  db: Database.Database,
  id: string,
): void {
  db.prepare(
    `UPDATE patterns
     SET dismissed_count = dismissed_count + 1, updated_at = datetime('now')
     WHERE id = ?`,
  ).run(id);
}

/**
 * Enables or disables a pattern.
 */
export function setPatternEnabled(
  db: Database.Database,
  id: string,
  enabled: boolean,
): void {
  db.prepare(
    `UPDATE patterns
     SET enabled = ?, updated_at = datetime('now')
     WHERE id = ?`,
  ).run(enabled ? 1 : 0, id);
}
